// Generated by hand for the fast CSR branch.
// In a normal R development environment, rerun Rcpp::compileAttributes().

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FastSpatialMeat
arma::mat FastSpatialMeat(arma::vec lat, arma::vec lon, arma::vec time,
                          arma::mat X, arma::vec e, double cutoff,
                          std::string kernel, std::string dist_fn,
                          bool balanced_pnl, int ncores);
RcppExport SEXP _fastconley_FastSpatialMeat(SEXP latSEXP, SEXP lonSEXP, SEXP timeSEXP,
                                        SEXP XSEXP, SEXP eSEXP, SEXP cutoffSEXP,
                                        SEXP kernelSEXP, SEXP dist_fnSEXP,
                                        SEXP balanced_pnlSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lat(latSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e(eSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist_fn(dist_fnSEXP);
    Rcpp::traits::input_parameter< bool >::type balanced_pnl(balanced_pnlSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSpatialMeat(lat, lon, time, X, e, cutoff,
                                                 kernel, dist_fn, balanced_pnl, ncores));
    return rcpp_result_gen;
END_RCPP
}

// TimeDist
arma::mat TimeDist(arma::vec times, double cutoff, arma::mat X, arma::vec e,
                   int n1, int k, int ncores);
RcppExport SEXP _fastconley_TimeDist(SEXP timesSEXP, SEXP cutoffSEXP, SEXP XSEXP,
                                 SEXP eSEXP, SEXP n1SEXP, SEXP kSEXP,
                                 SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type times(timesSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(TimeDist(times, cutoff, X, e, n1, k, ncores));
    return rcpp_result_gen;
END_RCPP
}

// FastSerialHacPanel
arma::mat FastSerialHacPanel(arma::vec unit, arma::vec time, double cutoff,
                             arma::mat X, arma::vec e, int ncores);
RcppExport SEXP _fastconley_FastSerialHacPanel(SEXP unitSEXP, SEXP timeSEXP, SEXP cutoffSEXP,
                                               SEXP XSEXP, SEXP eSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSerialHacPanel(unit, time, cutoff, X, e, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastconley_FastSpatialMeat", (DL_FUNC) &_fastconley_FastSpatialMeat, 10},
    {"_fastconley_TimeDist", (DL_FUNC) &_fastconley_TimeDist, 7},
    {"_fastconley_FastSerialHacPanel", (DL_FUNC) &_fastconley_FastSerialHacPanel, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastconley(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
