// Generated by hand for the fast CSR branch.
// In a normal R development environment, rerun Rcpp::compileAttributes().

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FastSpatialMeat
arma::mat FastSpatialMeat(Rcpp::NumericVector lat, Rcpp::NumericVector lon,
                          Rcpp::NumericVector time, Rcpp::NumericMatrix scores,
                          double cutoff, std::string kernel, std::string dist_fn,
                          bool balanced_pnl, int ncores, std::string neighbor,
                          std::string csr_weight);
RcppExport SEXP _fastconley_FastSpatialMeat(SEXP latSEXP, SEXP lonSEXP, SEXP timeSEXP,
                                        SEXP scoresSEXP, SEXP cutoffSEXP,
                                        SEXP kernelSEXP, SEXP dist_fnSEXP,
                                        SEXP balanced_pnlSEXP, SEXP ncoresSEXP,
                                        SEXP neighborSEXP, SEXP csr_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist_fn(dist_fnSEXP);
    Rcpp::traits::input_parameter< bool >::type balanced_pnl(balanced_pnlSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< std::string >::type neighbor(neighborSEXP);
    Rcpp::traits::input_parameter< std::string >::type csr_weight(csr_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSpatialMeat(lat, lon, time, scores, cutoff,
                                                 kernel, dist_fn, balanced_pnl,
                                                 ncores, neighbor, csr_weight));
    return rcpp_result_gen;
END_RCPP
}

// FastSerialHacPanel
arma::mat FastSerialHacPanel(Rcpp::NumericVector unit, Rcpp::NumericVector time,
                             double cutoff, Rcpp::NumericMatrix scores, int ncores);
RcppExport SEXP _fastconley_FastSerialHacPanel(SEXP unitSEXP, SEXP timeSEXP, SEXP cutoffSEXP,
                                               SEXP scoresSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSerialHacPanel(unit, time, cutoff, scores, ncores));
    return rcpp_result_gen;
END_RCPP
}

// FastGridMeat
arma::mat FastGridMeat(Rcpp::IntegerVector ring, Rcpp::IntegerVector col,
                       Rcpp::NumericVector time, Rcpp::NumericMatrix scores,
                       double lat0, double dlat, double dlon,
                       int n_ring, int n_col, int n_col_full,
                       double cutoff, std::string dist_fn, std::string kernel,
                       int ncores);
RcppExport SEXP _fastconley_FastGridMeat(SEXP ringSEXP, SEXP colSEXP, SEXP timeSEXP,
                                         SEXP scoresSEXP, SEXP lat0SEXP, SEXP dlatSEXP,
                                         SEXP dlonSEXP, SEXP n_ringSEXP, SEXP n_colSEXP,
                                         SEXP n_col_fullSEXP, SEXP cutoffSEXP,
                                         SEXP dist_fnSEXP, SEXP kernelSEXP,
                                         SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ring(ringSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type col(colSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< double >::type lat0(lat0SEXP);
    Rcpp::traits::input_parameter< double >::type dlat(dlatSEXP);
    Rcpp::traits::input_parameter< double >::type dlon(dlonSEXP);
    Rcpp::traits::input_parameter< int >::type n_ring(n_ringSEXP);
    Rcpp::traits::input_parameter< int >::type n_col(n_colSEXP);
    Rcpp::traits::input_parameter< int >::type n_col_full(n_col_fullSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist_fn(dist_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(FastGridMeat(ring, col, time, scores, lat0, dlat,
                                              dlon, n_ring, n_col, n_col_full,
                                              cutoff, dist_fn, kernel, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastconley_FastSpatialMeat", (DL_FUNC) &_fastconley_FastSpatialMeat, 11},
    {"_fastconley_FastSerialHacPanel", (DL_FUNC) &_fastconley_FastSerialHacPanel, 5},
    {"_fastconley_FastGridMeat", (DL_FUNC) &_fastconley_FastGridMeat, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastconley(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
