# Generated by hand for the fast CSR branch.
# In a normal R development environment, rerun Rcpp::compileAttributes().

# The C++ entry points alias R memory directly (no input copies) and assume
# REALSXP storage, so the wrappers coerce here. `scores` is the score matrix
# e * X (possibly pre-aggregated); passing `X` and `e` instead is supported
# for convenience and computes `scores <- X * e` once.

.as_dbl_vector <- function(x) {
  if (is.double(x)) x else as.numeric(x)
}

.as_dbl_matrix <- function(m) {
  if (!is.matrix(m)) m <- as.matrix(m)
  if (!is.double(m)) storage.mode(m) <- "double"
  m
}

FastSpatialMeat <- function(lat, lon, time, X = NULL, e = NULL, cutoff,
                            kernel = "bartlett", dist_fn = "haversine",
                            balanced_pnl = FALSE, ncores = 1L,
                            neighbor = "grid", scores = NULL,
                            csr_weight = "double") {
  if (is.null(scores)) scores <- X * e
  RcppParallel::setThreadOptions(numThreads = as.integer(max(1L, ncores)))
  .Call(`_fastconley_FastSpatialMeat`,
        .as_dbl_vector(lat), .as_dbl_vector(lon), .as_dbl_vector(time),
        .as_dbl_matrix(scores), cutoff, kernel, dist_fn, balanced_pnl,
        ncores, neighbor, csr_weight)
}

FastSerialHacPanel <- function(unit, time, cutoff, X = NULL, e = NULL,
                               ncores = 1L, scores = NULL) {
  if (is.null(scores)) scores <- X * e
  RcppParallel::setThreadOptions(numThreads = as.integer(max(1L, ncores)))
  .Call(`_fastconley_FastSerialHacPanel`,
        .as_dbl_vector(unit), .as_dbl_vector(time), cutoff,
        .as_dbl_matrix(scores), ncores)
}
