# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastSpatialMeat_cpp <- function(lat, lon, time, scores, cutoff, kernel = "bartlett", dist_fn = "haversine", balanced_pnl = FALSE, ncores = 1L, neighbor = "grid", csr_weight = "double") {
    .Call(`_fastconley_FastSpatialMeat_cpp`, lat, lon, time, scores, cutoff, kernel, dist_fn, balanced_pnl, ncores, neighbor, csr_weight)
}

FastSerialHacPanel_cpp <- function(unit, time, cutoff, scores, ncores = 1L) {
    .Call(`_fastconley_FastSerialHacPanel_cpp`, unit, time, cutoff, scores, ncores)
}

FastGridMeat_cpp <- function(ring, col, time, scores, lat0, dlat, dlon, n_ring, n_col, n_col_full, cutoff, dist_fn = "spherical", kernel = "uniform", ncores = 1L) {
    .Call(`_fastconley_FastGridMeat_cpp`, ring, col, time, scores, lat0, dlat, dlon, n_ring, n_col, n_col_full, cutoff, dist_fn, kernel, ncores)
}

